# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('sender', models.CharField(blank=True, max_length=40, null=True)),
                ('date_delivered', models.DateField(auto_now_add=True)),
                ('date_received', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', pgcrypto.fields.EncryptedEmailField(charset='utf-8', check_armor=True, cipher='AES', verbose_name='Email address', versioned=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(700)])),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Resident')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Room')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Room'),
        ),
    ]
