# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='enabled',
        ),
    ]
